[package]
name = "helper"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "=0.13.3", features = [
  "arithmetic",
  "serde",
  "expose-field",
  "std",
  "ecdsa",
], default-features = false }
base64 = "0.22.1"
hex = "0.4.3"
