[workspace]
[package]
version = "0.1.0"
name = "sha2-bench"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "v4.0.1" }
sha2 = { version = "0.10.8", default-features = false }
