[workspace]
[package]
version = "0.1.0"
name = "sha2-chain"
edition = "2021"

[dependencies]
zkm-runtime = { git = "https://github.com/zkMIPS/zkm", branch = "main", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
