[workspace]
[package]
version = "0.1.0"
name = "sha3-bench"
edition = "2021"

[dependencies]
zkm-runtime = { git = "https://github.com/zkMIPS/zkm", branch = "main", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
